SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;



SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES JOIN DEPARTMENTS
USING (DEPARTMENT_ID);



-- EMPLOYEE NAME AND CORRESPONDING MANAGER NAME
SELECT M.FIRST_NAME AS EMPLOYEE_NAME, E.FIRST_NAME AS MANAGER_NAME
FROM EMPLOYEES AS E 
JOIN EMPLOYEES AS M
ON E.EMPLOYEE_ID = M.MANAGER_ID
;

-- JEI DEPARTMENT A KONO EMPLOYEE NAI
SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
LEFT JOIN EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL
;


-- EKJON EMPLOYEE TAR DEPARTMENT ER AVERAGE SALARY..
-- THEKE KOTO TAKA KOM PAAY
SELECT 
		EMPLOYEES.FIRST_NAME, 
		EMPLOYEES.SALARY,
		(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID)-EMPLOYEES.SALARY AS SAL_DIFF
FROM EMPLOYEES
	JOIN DEPARTMENTS
	ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
;


-- JEI DEPARTMENT GULOR MINIMUM SALARY 5000 ER CHEYE BESHI
SELECT DEPARTMENT_NAME, MIN(SALARY), AVG(SALARY)
FROM EMPLOYEES 
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING MIN(SALARY) > 5000
;




