

ALTER TABLE COURSE RENAME SCHOOL_COURSES
;

CREATE TABLE Instructor (	
    InstructorID INT AUTO_INCREMENT PRIMARY KEY,	
    Name VARCHAR(255) NOT NULL,	
    Email VARCHAR(255) NOT NULL UNIQUE,	
    Phone VARCHAR(15),	
    Department VARCHAR(50),
	Salary DECIMAL(10,2)
);

INSERT INTO INSTRUCTOR (NAME,EMAIL,PHONE,DEPARTMENT,SALARY)
VALUES
('Jahangir Alam','jahangir@gmail.com','87642366','CSE',35000),
('Mohammad Ali','mohammad@gmail.com','97432366','CSE',27000),
('Zia Hasan','ziahasangmail.com','886542366','CSE',33000),
('Hasanul Haque','hasanul@gmail.com','34234366','CSE',25000)
;	

SELECT *
FROM INSTRUCTOR
;

WITH T_1 AS 
(
	SELECT MAX(SALARY) AS MAX_SAL_1
    FROM INSTRUCTOR
)

SELECT I.INSTRUCTORID, I.NAME, I.EMAIL, I.PHONE, I.DEPARTMENT,I.SALARY AS 2ND_MAX_SALARY
FROM INSTRUCTOR I
WHERE SALARY < (SELECT MAX_SAL_1 FROM T_1)
ORDER BY SALARY DESC
LIMIT 1
;


CREATE TABLE Course (	
    CourseID INT AUTO_INCREMENT PRIMARY KEY,	
    Title VARCHAR(255) NOT NULL,	
    Credits INT NOT NULL,	
    InstructorID INT,	
    FOREIGN KEY (InstructorID) REFERENCES Instructor(InstructorID) ON DELETE CASCADE	
);


INSERT INTO COURSE(TITLE,CREDITS,INSTRUCTORID)
VALUES
('CSE101',3,4),
('CSE104',1,1),
('CSE208',3,2),
('CSE312',2,3)
;



DELETE 
FROM INSTRUCTOR
WHERE INSTRUCTORID = 4
;

SELECT *
FROM COURSE
;
