-- 1 SECOND MAX SALARY USING LIMIT, OFFSET
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1,5
;

-- SECOND MAX SALARY USING SUBQUERY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (
				SELECT MAX(SALARY)
				FROM EMPLOYEES
				WHERE SALARY < (
								SELECT MAX(SALARY)
								FROM EMPLOYEES
								)
			);



SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (
			SELECT MAX(SALARY)
            FROM EMPLOYEES
);




-- 2 KON KON EMPLOYEE TADER MANAGER ER THEKE BESHI SALARY PAAY
SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (
				SELECT SALARY
                FROM EMPLOYEES AS MGR 
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
                
);


-- 3 KON KON EMPLOYEE TAR NIJER MANAGER ER MOTO SAME JOB KORE
SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (
				SELECT JOB_ID
                FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
);





