USE DUMMYDB;

SELECT * 
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 144
;

-- 1 EMP ID 144 ER CHEYE KOM SALARY KARA PAAY?
SELECT * 
FROM EMPLOYEES
WHERE SALARY < (
				SELECT SALARY
				FROM EMPLOYEES
				WHERE EMPLOYEE_ID = 144
)
;


-- 2 KON EMPLOYEE TA HIGHEST SALARY PAAY?alter
SELECT * 
FROM EMPLOYEES 
WHERE SALARY = (
				SELECT MAX(SALARY)
				FROM EMPLOYEES
);
-- SUB QUERY
SELECT MAX(SALARY)
FROM EMPLOYEES;




-- 3 MARKETING DEPARTMENT A KARA KARA KAJ KORE
SELECT *
FROM DEPARTMENTS;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
						SELECT DEPARTMENT_ID 
                        FROM DEPARTMENTS 
                        WHERE DEPARTMENT_NAME = "MARKETING"
); 


-- 4 MARKETING DEPARTMENT ER AVERAGE SALARY KOTO
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
					SELECT DEPARTMENT_ID 
                    FROM DEPARTMENTS 
                    WHERE DEPARTMENT_NAME = "MARKETING"
);


-- MARKETING DEPARTMENT ER MAX SALARY K PAAY

SELECT * 
FROM EMPLOYEES
WHERE SALARY = (
				SELECT MAX(SALARY)
				FROM EMPLOYEES
				WHERE DEPARTMENT_ID = (
					SELECT DEPARTMENT_ID
                    FROM DEPARTMENTS
                    WHERE DEPARTMENT_NAME = "MARKETING"
                    )

);



-- 5 IT DEPARTMENT A KOYJON KAJ KORE
SELECT COUNT(*) AS MEMBERS
FROM EMPLOYEES
WHERE DEPARTMENT_ID = ( 
						SELECT DEPARTMENT_ID
						FROM DEPARTMENTS
                        WHERE DEPARTMENT_NAME = "IT"
);





-- 6 PROGRAMMER DER TOTAL SALARY KOTO
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
					SELECT DEPARTMENT_ID
                    FROM DEPARTMENTS
                    WHERE DEPARTMENT_NAME="IT"
);


SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = (
				SELECT JOB_ID
				FROM JOBS
				WHERE JOB_TITLE = "PROGRAMMER"

);




SELECT *
FROM JOBS


