USE DUMMYDB;

-- 2 
SELECT M.EMPLOYEE_ID AS EMP_ID, M.MANAGER_ID,M.FIRST_NAME AS EMP_FIRST_NAME
FROM EMPLOYEES AS E
JOIN EMPLOYEES AS M
ON E.EMPLOYEE_ID = M.MANAGER_ID
;

-- 2 (SUBMITTED THIS FORMAT)
SELECT M.FIRST_NAME AS EMP_FIRST_NAME, M.MANAGER_ID
FROM EMPLOYEES AS E
JOIN EMPLOYEES AS M
ON E.EMPLOYEE_ID = M.MANAGER_ID
;

-- 4
SELECT *
FROM EMPLOYEES;

SELECT MAX(SALARY) AS THIRD_HIGHEST_SALARY
FROM EMPLOYEES
WHERE SALARY < 
			(
				SELECT MAX(SALARY)
                FROM EMPLOYEES
                WHERE SALARY < 
							(
								SELECT MAX(SALARY)	
                                FROM EMPLOYEES
                            )
            
            );
            
            
            
-- 5
SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, COUNT(*) AS NUMBER_OF_EMPLOYEES
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_ID
;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;




-- 8
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = (
						SELECT EMPLOYEE_ID
                        FROM EMPLOYEES
                        WHERE FIRST_NAME = "STEVEN" AND LAST_NAME = "KING"
					)
;


SELECT FIRST_NAME,LAST_NAME
FROM EMPLOYEES
WHERE SALARY < 
		(
			SELECT SALARY
			FROM EMPLOYEES
			WHERE EMPLOYEE_ID = (
						SELECT EMPLOYEE_ID
                        FROM EMPLOYEES
                        WHERE FIRST_NAME = "STEVEN" AND LAST_NAME = "KING"
					)

        )
        
;




-- 9
SELECT DEPARTMENTS.DEPARTMENT_ID,DEPARTMENTS.DEPARTMENT_NAME,EMPLOYEES.EMPLOYEE_ID AS MGR_ID, CONCAT( EMPLOYEES.FIRST_NAME,' ', EMPLOYEES.LAST_NAME) AS MGR_NAME
FROM DEPARTMENTS
LEFT JOIN EMPLOYEES
ON DEPARTMENTS.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID
;

-- 9 (SUBMITTED THIS)
SELECT DEPARTMENTS.DEPARTMENT_NAME, CONCAT( EMPLOYEES.FIRST_NAME,' ', EMPLOYEES.LAST_NAME) AS MGR_NAME
FROM DEPARTMENTS
LEFT JOIN EMPLOYEES
ON DEPARTMENTS.MANAGER_ID = EMPLOYEES.EMPLOYEE_ID
;


-- 10
SELECT DEPARTMENTS.DEPARTMENT_NAME,LOCATIONS.CITY
FROM DEPARTMENTS
JOIN LOCATIONS
ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
;

SELECT DISTINCT CITY
FROM LOCATIONS;
