CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE STUDENT(
	ROLL VARCHAR(4),
    NAME VARCHAR(50) NOT NULL,
    GRADE VARCHAR(10) NOT NULL,
    ADDRESS VARCHAR(70) NOT NULL,
    PHONE_NO VARCHAR(13),
    
    CONSTRAINT PRIMARY_KEY_RULE PRIMARY KEY(ROLL),
    CONSTRAINT PHONE_NO_RULE UNIQUE(PHONE_NO)
);


CREATE TABLE LIBRARY(
	BOOK_NAME VARCHAR(40) UNIQUE,
    WHO_BORROWED VARCHAR(4),
	CONSTRAINT FRG_KEY_RULE FOREIGN KEY(WHO_BORROWED) REFERENCES STUDENT(ROLL)
);


CREATE TABLE FEES (
	INVOICE_NO INT,
    STUD_ID VARCHAR(4) NOT NULL,
    STUD_GRADE VARCHAR(10) NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    
    CONSTRAINT ID_RULE UNIQUE(STUD_ID),
    CONSTRAINT COMP_PRM_KEY_RULE PRIMARY KEY(STUD_ID,STUD_GRADE)

);


INSERT INTO STUDENT(ROLL,NAME,GRADE,ADDRESS,PHONE_NO)
VALUES
("001","Rakib","Nine","Uttara Sector 4","01354785563"),
("002","Nayem","Seven","Uttara Sector 9","0171269828");

INSERT INTO LIBRARY(BOOK_NAME,WHO_BORROWED)
VALUES
("Basic C++","001"),
("DSA","002");

INSERT INTO FEES(INVOICE_NO,STUD_ID,STUD_GRADE,AMOUNT)
VALUES
(1,"001","Nine",5400.0),
(2,"002","Seven",7600.0);



-- 5
USE BRAIN_STATION;

SELECT DISTINCT DEPARTMENT
FROM EMPLOYEE;

-- 6
SELECT LASTNAME, AGE
FROM EMPLOYEE
ORDER BY AGE DESC;

-- 7
SELECT LASTNAME,AGE,DEPARTMENT
FROM EMPLOYEE
WHERE AGE > 30 AND DEPARTMENT = "MARKETING";


-- 8
SELECT * FROM EMPLOYEE;



-- 9
SELECT * 
FROM EMPLOYEE
WHERE LASTNAME LIKE '%son%';


-- 10
SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT = "ENGINEERING";


